"""Auto-diagnosis: called by GitHub Actions when health check fails.

Collects context passed via env vars, calls Claude API to diagnose,
posts findings as a GitHub issue comment (or creates an issue if none exists).

Required env vars:
  ANTHROPIC_API_KEY
  GH_TOKEN               — GitHub token (set automatically in Actions)
  GH_REPO                — owner/repo  (e.g. cdelvalle81282/samcart-analytics)
  FAILURE_CONTEXT        — JSON string: {checks: [{name, error}], logs: str}

Optional:
  ISSUE_NUMBER           — existing issue to comment on (else creates new one)
"""

import json
import os
import sys

import requests

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
GH_API = "https://api.github.com"

SYSTEM_PROMPT = """\
You are an on-call SRE assistant for a Streamlit analytics dashboard deployed on a DigitalOcean droplet.
The stack is: Python 3.12, Streamlit, SQLite (WAL), systemd service named samcart-analytics, nginx reverse proxy, Certbot SSL.
The app is at https://opisamcart.duckdns.org and the repo is on GitHub.

When given a health check failure report with server logs, you:
1. Identify the root cause concisely.
2. State whether it is auto-recoverable (e.g. OOM restart, disk full, crashed process) or needs a code fix.
3. Provide the exact shell commands to fix it if recoverable, or a clear description of what code change is needed.
4. Keep the response under 400 words. Use GitHub-flavored markdown.
"""


def call_claude(api_key: str, context: dict) -> str:
    checks_summary = "\n".join(
        f"- **{c['name']}**: {c['error']}" for c in context.get("checks", [])
    )
    logs = context.get("logs", "(no logs collected)")

    user_message = f"""## Health Check Failure Report

### Failed checks
{checks_summary}

### Server logs (last 100 lines)
```
{logs[:6000]}
```

What is the root cause and how should it be fixed?
"""

    resp = requests.post(
        ANTHROPIC_API_URL,
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": "claude-opus-4-7",
            "max_tokens": 1024,
            "system": SYSTEM_PROMPT,
            "messages": [{"role": "user", "content": user_message}],
        },
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json()["content"][0]["text"]


def gh_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}


def create_issue(token: str, repo: str, context: dict) -> int:
    checks_summary = "\n".join(
        f"- **{c['name']}**: {c['error']}" for c in context.get("checks", [])
    )
    logs = context.get("logs", "(no logs collected)")
    body = f"""## Automated Health Check Failure

### Failed checks
{checks_summary}

### Server logs
```
{logs[:6000]}
```

_Created automatically by the health check workflow._
"""
    resp = requests.post(
        f"{GH_API}/repos/{repo}/issues",
        headers=gh_headers(token),
        json={"title": "Health check failure", "body": body, "labels": ["health-alert"]},
        timeout=15,
    )
    resp.raise_for_status()
    number = resp.json()["number"]
    print(f"Created issue #{number}")
    return number


def post_comment(token: str, repo: str, issue_number: int, body: str) -> None:
    resp = requests.post(
        f"{GH_API}/repos/{repo}/issues/{issue_number}/comments",
        headers=gh_headers(token),
        json={"body": body},
        timeout=15,
    )
    resp.raise_for_status()
    print(f"Posted comment on issue #{issue_number}")


def main() -> int:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    gh_token = os.environ.get("GH_TOKEN", "")
    repo = os.environ.get("GH_REPO", "")
    raw_context = os.environ.get("FAILURE_CONTEXT", "{}")
    issue_number_env = os.environ.get("ISSUE_NUMBER", "")

    try:
        context = json.loads(raw_context)
    except json.JSONDecodeError:
        context = {"checks": [], "logs": raw_context}

    # Create or reuse issue
    if issue_number_env:
        issue_number = int(issue_number_env)
    elif gh_token and repo:
        issue_number = create_issue(gh_token, repo, context)
    else:
        print("No GH_TOKEN/GH_REPO — skipping issue creation")
        issue_number = None

    # Auto-diagnose if API key available
    if api_key:
        print("Calling Claude for diagnosis...")
        try:
            diagnosis = call_claude(api_key, context)
            comment = f"## Claude Diagnosis\n\n{diagnosis}\n\n_Auto-generated by diagnose.py_"
            if issue_number and gh_token and repo:
                post_comment(gh_token, repo, issue_number, comment)
            else:
                print(comment)
        except Exception as exc:
            print(f"Diagnosis failed: {exc}", file=sys.stderr)
    else:
        print("ANTHROPIC_API_KEY not set — skipping auto-diagnosis.")
        if issue_number:
            print(f"Issue #{issue_number} created with logs. Open Claude Code and run: investigate issue #{issue_number}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
