[server]
address = "127.0.0.1"
port = 8501
headless = true

[client]
showErrorDetails = false

[theme]
base = "dark"
primaryColor = "#B8FF57"
backgroundColor = "#07080E"
secondaryBackgroundColor = "#0D0F1A"
textColor = "#E8ECF8"
font = "sans serif"
widgetBackgroundColor = "#0D0F1A"
widgetBorderColor = "#1A1D2E"
skeletonBackgroundColor = "#1A1D2E"

[theme.sidebar]
backgroundColor = "#060709"
textColor = "#E8ECF8"
primaryColor = "#B8FF57"
widgetBackgroundColor = "#0D0F1A"
widgetBorderColor = "#1A1D2E"
skeletonBackgroundColor = "#1A1D2E"
